[tool.poetry]
name = "datastruct"
version = "0.1.0"
description = ""
authors = ["Skulsik_coder <skulsik1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
unitest = "^1.4.30"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
